"""Hidden extracurricular activities

Revision ID: 11e9b9f16f6f
Revises: 1a2439dedf1c
Create Date: 2026-08-30 06:59:17.565355+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e9b9f16f6f'
down_revision: Union[str, Sequence[str], None] = '1a2439dedf1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_extracurricular_activities',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='Идентификатор профиля (ребенка)'),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='Название предмета внеурочного занятия'),
    sa.Column('place', sa.String(length=32), nullable=False, comment='Место проведения (кабинет) внеурочного занятия'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', 'subject', 'place', name='hidden_extracurricular_activities_parent_id_child_id_subject_pl')
    )
    op.create_index('hidden_extracurricular_activities_created_at', 'hidden_extracurricular_activities', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE TRIGGER update_hidden_extracurricular_activities_updated_at BEFORE UPDATE ON hidden_extracurricular_activities FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hidden_extracurricular_activities_created_at', table_name='hidden_extracurricular_activities')
    op.drop_table('hidden_extracurricular_activities')
    # ### end Alembic commands ###
