"""ads

Revision ID: 1a2439dedf1c
Revises: cfd65bf7037a
Create Date: 2026-08-27 10:43:48.970577+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2439dedf1c'
down_revision: Union[str, Sequence[str], None] = 'cfd65bf7037a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('ad_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор рекламной единицы'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='Идентификатора пользователя в Telegram, который управляет рекламой'),
    sa.Column('school_id', sa.BigInteger(), nullable=True, comment='Идентификатор образовательной организации, в которой доступна реклама'),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='Идентификатор учебной группы (класса), в которой доступна реклама'),
    sa.Column('title', sa.String(length=32), nullable=False, comment='Заголовок рекламы'),
    sa.Column('text', sa.String(length=128), nullable=False, comment='Текст рекламы'),
    sa.Column('has_image', sa.Boolean(), nullable=False, comment='Наличие у рекламы собственной картинки'),
    sa.Column('url', sa.String(length=1024), nullable=False, comment='URL, на который будет перенаправлен пользователь при открытии рекламы'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='Количество доступных показов'),
    sa.Column('clicks', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Количество кликов на рекламу'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('ad_id', name='ads_ad_id')
    )
    op.create_index('ads_created_at', 'ads', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ads_school_id_group_id_balance', 'ads', ['school_id', 'group_id', 'balance'], unique=False)
    op.create_index('ads_user_id', 'ads', ['user_id'], unique=False)
    op.create_table('ad_viewings',
    sa.Column('ad_id', sa.BigInteger(), nullable=False, comment='Идентификатор рекламной единицы'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('last_viewing', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Время последнего показа рекламы пользователю'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.ad_id'], name='ad_viewings_ad_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='ad_viewings_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ad_id', 'parent_id', name='ad_viewings_ad_id_parent_id')
    )
    op.create_index('ad_viewings_created_at', 'ad_viewings', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE TRIGGER update_ads_updated_at BEFORE UPDATE ON ads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_ad_viewings_updated_at BEFORE UPDATE ON ad_viewings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ad_viewings_created_at', table_name='ad_viewings')
    op.drop_table('ad_viewings')
    op.drop_index('ads_user_id', table_name='ads')
    op.drop_index('ads_school_id_group_id_balance', table_name='ads')
    op.drop_index('ads_created_at', table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
