"""TgBot Callback Data

Revision ID: 1df5d7c26d31
Revises: 11e9b9f16f6f
Create Date: 2026-09-13 06:31:38.654014+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df5d7c26d31'
down_revision: Union[str, Sequence[str], None] = '11e9b9f16f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgbot_callback_data',
    sa.Column('module', sa.String(length=15), nullable=False, comment='Идентификатор модуля Telegram-бота'),
    sa.Column('action', sa.String(length=15), nullable=False, comment='Действие, совершаемое по кнопке'),
    sa.Column('key', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Ключ данных кнопки'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Данные кнопки'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('module', 'action', 'key', name='tgbot_callback_data_module_key')
    )
    op.create_index('tgbot_callback_data_created_at', 'tgbot_callback_data', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tgbot_callback_data_created_at', table_name='tgbot_callback_data')
    op.drop_table('tgbot_callback_data')
    # ### end Alembic commands ###
