"""Teacher tools

Revision ID: a730ae145e65
Revises: fb0b496e76fa
Create Date: 2026-10-03 12:25:43.837039+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a730ae145e65'
down_revision: Union[str, Sequence[str], None] = 'e55a0298e395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор учителя (Идентификатор персоны (person_id) в Дневнике.ру)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id', name='teachers_teacher_id')
    )
    op.create_index('teachers_created_at', 'teachers', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('teacher_sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии учителя'),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False, comment='Идентификатор учителя'),
    sa.Column('dnevnik_token', sa.String(length=64), nullable=False, comment='API-токен Дневника.ру для взаимодействия с ним'),
    sa.Column('life', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Сессия активна или больше не работает'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name='teacher_sessions_teacher_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name='teacher_sessions_pkey')
    )
    op.create_index('teacher_sessions_created_at', 'teacher_sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('teacher_sessions_life_teacher_id_session_id', 'teacher_sessions', ['life', 'teacher_id', 'session_id'], unique=False)
    op.create_index('teacher_sessions_teacher_id_life_session_id', 'teacher_sessions', ['teacher_id', 'life', 'session_id'], unique=False)
    op.create_index('teacher_sessions_teacher_id_session_id', 'teacher_sessions', ['teacher_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('teacher_sessions_teacher_id_session_id', table_name='teacher_sessions')
    op.drop_index('teacher_sessions_teacher_id_life_session_id', table_name='teacher_sessions')
    op.drop_index('teacher_sessions_life_teacher_id_session_id', table_name='teacher_sessions')
    op.drop_index('teacher_sessions_created_at', table_name='teacher_sessions')
    op.drop_table('teacher_sessions')
    op.drop_index('teachers_created_at', table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
