"""Initial migration

Revision ID: ce5a2755b274
Revises: 
Create Date: 2026-05-17 11:18:52.167990+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce5a2755b274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('child_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор ребенка'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='Идентификатор образовательной организации в Дневнике.ру'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='Идентификатор учебной группы (класса) в Дневнике.ру'),
    sa.Column('timezone', sa.Integer(), nullable=False, comment='Часовой пояс ребенка в секундах'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('child_id', name='children_user_id')
    )
    op.create_index('children_created_at', 'children', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('children_school_id_group_id_child_id', 'children', ['school_id', 'group_id', 'child_id'], unique=False)
    op.create_table('extracurricular_activities',
    sa.Column('ea_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор внеурочного занятия'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='Идентификатор образовательной организации в Дневнике.ру'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='Идентификатор учебной группы (класса) в Дневнике.ру'),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время начала внеурочного занятия'),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='Название предмета внеурочного занятия'),
    sa.Column('place', sa.String(length=32), nullable=False, comment='Место проведения (кабинет) внеурочного занятия'),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Часы проведения внеурочного занятия'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('ea_id', name='extracurricular_activities_pkey'),
    sa.UniqueConstraint('school_id', 'group_id', 'start_time', 'subject', 'place', name='extracurricular_activities_school_id_group_id_start_time_subjec')
    )
    op.create_index('extracurricular_activities_created_at', 'extracurricular_activities', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('extracurricular_activities_start_time_subject_place', 'extracurricular_activities', ['start_time', 'subject', 'place'], unique=False)
    op.create_table('hours',
    sa.Column('hour_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор данных'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='Идентификатор образовательной организации в Дневнике.ру'),
    sa.Column('months', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Список месяцев (номера), в которых действует расписание'),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Список дней недели (индексы), в которых действует расписание'),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Список расписания звонков для каждого урока'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('hour_id', name='hours_hour_id')
    )
    op.create_index('hours_created_at', 'hours', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('hours_school_id_months_weekdays', 'hours', ['school_id', 'months', 'weekdays'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор лога'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='IP-адрес, с которого совершен запрос, или модуль проекта, в котором записан лог'),
    sa.Column('path', sa.Text(), nullable=False, comment='Путь запроса или другая информация о месте записи лога'),
    sa.Column('session_id', sa.String(length=32), nullable=True, comment='Идентификатор сессии, с которого сделан запрос'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Успех операции'),
    sa.Column('method', sa.String(length=32), nullable=True, comment='HTTP-метод запроса'),
    sa.Column('value', sa.Text(), nullable=False, comment='Данные лога'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('log_id', name='logs_log_id')
    )
    op.create_index('logs_created_at', 'logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('logs_status_created_at', 'logs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('monitorings',
    sa.Column('monitoring_id', sa.BigInteger(), sa.Identity(always=False), nullable=False, comment='Идентификатор записи мониторинга'),
    sa.Column('path', sa.String(length=128), nullable=False, comment='Путь запроса'),
    sa.Column('session_id', sa.String(length=32), nullable=True, comment='Идентификатор сессии'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Статус запроса (отсутствие ошибки в процессе обработки)'),
    sa.Column('duration', sa.Interval(), nullable=False, comment='Время обработки запроса'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('monitoring_id', name='monitorings_monitoring_id')
    )
    op.create_index('monitorings_created_at', 'monitorings', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('monitorings_path_duration', 'monitorings', ['path', sa.literal_column('duration DESC')], unique=False)
    op.create_index('monitorings_path_session_id_duration', 'monitorings', ['path', 'session_id', sa.literal_column('duration DESC')], unique=False)
    op.create_index('monitorings_status_path_duration', 'monitorings', [sa.literal_column('status DESC'), 'path', sa.literal_column('duration DESC')], unique=False)
    op.create_index('monitorings_status_path_session_id_duration', 'monitorings', [sa.literal_column('status DESC'), 'path', 'session_id', sa.literal_column('duration DESC')], unique=False)
    op.create_table('parents',
    sa.Column('parent_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя (Идентификатор персоны (person_id) в Дневнике.ру)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', name='parents_user_id')
    )
    op.create_index('parents_created_at', 'parents', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('school_admins',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор Telegram-аккаунта администратора образовательной организации'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Имя администратора образовательной организации'),
    sa.Column('parent_admin_id', sa.BigInteger(), nullable=True, comment='Идентификатор верхнего по уровню администратора образовательной организации (user_id)'),
    sa.Column('person_id', sa.BigInteger(), nullable=True, comment='Идентификатор персоны в Дневнике.ру (для самого верхнего по уровню администратора образовательной организации)'),
    sa.Column('school_id', sa.BigInteger(), nullable=True, comment='Идентификатор образовательной организации в Дневнике.ру (для самого верхнего по уровню администратора образовательной организации)'),
    sa.Column('timezone', sa.Integer(), nullable=True, comment='Часовой пояс в секундах (для самого верхнего по уровню администратора образовательной организации)'),
    sa.Column('dnevnik_token', sa.String(length=64), nullable=True, comment='API-токен Дневника.ру (для самого верхнего по уровню администратора образовательной организации)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('((((parent_admin_id IS NULL) <> (person_id IS NULL)) AND ((parent_admin_id IS NULL) <> (school_id IS NULL)) AND ((parent_admin_id IS NULL) <> (dnevnik_token IS NULL)) AND ((parent_admin_id IS NULL) <> (timezone IS NULL))))', name='check_type_admin'),
    sa.CheckConstraint('((user_id <> parent_admin_id))', name='check_no_self_admin'),
    sa.ForeignKeyConstraint(['parent_admin_id'], ['school_admins.user_id'], name='school_admins_parent_admin_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='school_admins_user_id')
    )
    op.create_index('school_admins_created_at', 'school_admins', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_admins_parent_admin_user_id', 'school_admins', ['parent_admin_id', 'user_id'], unique=False)
    op.create_index('school_admins_school_id_person_id', 'school_admins', ['school_id', 'person_id'], unique=False)
    op.create_index('school_admins_school_id_user_id', 'school_admins', ['school_id', 'user_id'], unique=False)
    op.create_table('school_posts',
    sa.Column('post_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор школьной публикации'),
    sa.Column('school_id', sa.BigInteger(), nullable=True, comment='Идентификатор образовательной организации в Дневнике.ру. Если не указано, то открыто для для всех'),
    sa.Column('timezone', sa.Integer(), nullable=False, comment='Часовой пояс в секундах'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='Заголовок публикации'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Описание публикации под заголовком'),
    sa.Column('has_image', sa.Boolean(), nullable=False, comment='Наличие главного изображения публикации'),
    sa.Column('author', sa.String(length=64), nullable=False, comment='Автор публикации (администратор образовательной организации или другое)'),
    sa.Column('author_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Автор является официальным лицом приложения'),
    sa.Column('schedule_date', sa.Date(), nullable=True, comment='Дата проведенного мероприятия'),
    sa.Column('is_updated', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Публикация была отредактирована'),
    sa.Column('count_visions', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Количество пользователей, которые увидели наличие публикации'),
    sa.Column('count_clicks', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Количество пользователей, которые открыли публикации'),
    sa.Column('count_viewings', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Количество полных просмотров публикации'),
    sa.Column('count_likes', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Количество реакции на публикацию'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Содержание публикации - последовательные заголовки, абзацы, фото и видео'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('((count_clicks >= 0))', name='check_count_clicks'),
    sa.CheckConstraint('((count_likes >= 0))', name='check_count_likes'),
    sa.CheckConstraint('((count_viewings >= 0))', name='check_count_views'),
    sa.CheckConstraint('((count_visions >= 0))', name='check_count_visions'),
    sa.PrimaryKeyConstraint('post_id', name='school_posts_post_id')
    )
    op.create_index('school_posts_created_at', 'school_posts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_posts_school_id_created_at', 'school_posts', ['school_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('statistic_messages',
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время сбора и анализа логов, мониторинга и статистики'),
    sa.Column('message', sa.Text(), nullable=False, comment='Итоговое сообщение с данными и анализом'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('time', name='statistic_messages_time')
    )
    op.create_index('statistic_messages_created_at', 'statistic_messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('statistics',
    sa.Column('statistic_id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='Идентификатор статистики'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='Идентификатор пользователя, совершившего действие'),
    sa.Column('key', sa.String(length=32), nullable=False, comment='Уникальный ключ действия'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('statistic_id', name='statistics_statistic_id')
    )
    op.create_index('statistics_created_at', 'statistics', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('statistics_parent_id_key', 'statistics', ['parent_id', 'key'], unique=False)
    op.create_table('tgbot_states',
    sa.Column('key', sa.String(length=128), nullable=False, comment='Ключ из чата и пользователя'),
    sa.Column('state', sa.String(length=128), nullable=True, comment='Состояние (действие, которое ожидается от пользователя)'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='Дополнительные данные к состоянию'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('key', name='tgbot_states_key')
    )
    op.create_index('tgbot_states_created_at', 'tgbot_states', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('versions',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False, comment='Номер сборки версии'),
    sa.Column('version', sa.String(length=16), nullable=False, comment='Строковая версия'),
    sa.Column('parent_version', sa.Integer(), nullable=True, comment='Главная версия группы'),
    sa.Column('status_id', sa.Numeric(), nullable=False, comment='Числовой статус, означающий важность обновления. (0;1]'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Строковый статус, означающий важность обновления'),
    sa.Column('info', sa.String(length=128), nullable=True, comment='Информационное сообщение, которое будет показана при запуске приложения с версией ниже'),
    sa.Column('logs', sa.Text(), nullable=False, comment='Список изменений, который будет показан пользователю'),
    sa.Column('date', sa.String(length=16), nullable=False, comment='Дата выпуска обновления в строковом формате DD.MM.YYYY'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version'], ['versions.number'], name='versions_parent_version_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('number', name='versions_pkey')
    )
    op.create_index('versions_created_at', 'versions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('ea_processing_notifications',
    sa.Column('ea_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор внеурочного занятия'),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='Время начала внеурочного занятия'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['extracurricular_activities.ea_id'], name='ea_processing_notifications_ea_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ea_id', name='ea_processing_notifications_ea_id')
    )
    op.create_index('ea_processing_notifications_created_at', 'ea_processing_notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ea_processing_notifications_start_time', 'ea_processing_notifications', ['start_time'], unique=False)
    op.create_table('highlighting_persons',
    sa.Column('parent_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('person_id', sa.BigInteger(), nullable=False, comment='Идентификатор персоны в Дневнике.ру, который будет выделен в рейтинге'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('((parent_id <> person_id))', name='check_no_self_person'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='highlighting_persons_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'person_id', name='highlighting_persons_parent_id_person_id')
    )
    op.create_index('highlighting_persons_created_at', 'highlighting_persons', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('informations',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False, comment='Целевое время информационного уведомления'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='Тип информации (для определенных действий после доставки)'),
    sa.Column('title', sa.String(length=32), nullable=False, comment='Заголовок информационного уведомления'),
    sa.Column('text', sa.String(length=128), nullable=False, comment='Текст информационного уведомления'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='informations_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'time', 'type', name='informations_parent_id_time_type')
    )
    op.create_index('informations_created_at', 'informations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('informations_time', 'informations', [sa.literal_column('time DESC')], unique=False)
    op.create_table('lesson_notes',
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='Идентификатор ребенка'),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False, comment='Идентификатор урока в Дневнике.ру, к которому прикреплена заметка'),
    sa.Column('text', sa.String(length=128), nullable=False, comment='Текст заметки'),
    sa.Column('public', sa.Boolean(), nullable=False, comment='Открытые заметки видны родителям ребенка'),
    sa.Column('remind_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время напоминания заметки'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name='lesson_notes_child_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id', 'lesson_id', name='lesson_notes_child_id_lesson_id')
    )
    op.create_index('lesson_notes_created_at', 'lesson_notes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('lesson_notes_lesson_id_child_id', 'lesson_notes', ['lesson_id', 'child_id'], unique=False)
    op.create_table('notifications',
    sa.Column('log_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор лога'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='IP-адрес, с которого совершен запрос, или модуль проекта, в котором записан лог'),
    sa.Column('path', sa.Text(), nullable=False, comment='Путь запроса или другая информация о месте записи лога'),
    sa.Column('session_id', sa.String(length=32), nullable=True, comment='Идентификатор сессии, с которого сделан запрос'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='Успех операции'),
    sa.Column('method', sa.String(length=32), nullable=True, comment='HTTP-метод запроса'),
    sa.Column('value', sa.Text(), nullable=False, comment='Данные лога'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.log_id'], name='notifications_log_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id', name='notifications_log_id')
    )
    op.create_index('notifications_created_at', 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('notifications_status_created_at', 'notifications', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('ratings',
    sa.Column('child_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор ребенка'),
    sa.Column('period_id', sa.BigInteger(), nullable=False, comment='Идентификатор отчетного периода в Дневнике.ру'),
    sa.Column('subject_id', sa.BigInteger(), nullable=False, comment='Идентификатор учебного предмета в Дневнике.ру или -1 для общего рейтинга в классе'),
    sa.Column('number', sa.SmallInteger(), nullable=False, comment='Порядковый номер ребенка в рейтинге (индекс - начало с 0)'),
    sa.Column('avg', sa.String(length=8), nullable=False, comment='Средний балл по предмету'),
    sa.Column('mood', sa.String(length=16), nullable=False, comment='Настроение оценки в Дневнике.ру'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name='ratings_child_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id', 'period_id', 'subject_id', name='ratings_child_id_period_id_subject_id')
    )
    op.create_index('ratings_created_at', 'ratings', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ratings_period_id_child_id_subject_id', 'ratings', ['period_id', 'child_id', 'subject_id'], unique=False)
    op.create_table('referrals',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя, который пригласил пользователя'),
    sa.Column('referral_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя, которого пригласили'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='Имя пригласившего (parent)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('((parent_id <> referral_id))', name='check_self_referral'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='referrals_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['parents.parent_id'], name='referrals_referral_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('referral_id', name='referrals_referral_id')
    )
    op.create_index('referrals_created_at', 'referrals', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('referrals_parent_id_referral_id', 'referrals', ['parent_id', 'referral_id'], unique=False)
    op.create_index('referrals_referral_id_parent_id', 'referrals', ['referral_id', 'parent_id'], unique=False)
    op.create_table('reviews',
    sa.Column('parent_id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='Имя пользователя, написавшего отзыв'),
    sa.Column('stars', sa.SmallInteger(), nullable=False, comment='Количество звезд в отзыве'),
    sa.Column('text', sa.String(length=512), nullable=True, comment='Текст отзыва'),
    sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Количество реакции на отзыве'),
    sa.Column('is_updated', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Отзыв был отредактирован'),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Отзыв открыт и доступен для показа или находится на модерации'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(((stars >= 1) AND (stars <= 5)))', name='check_stars'),
    sa.CheckConstraint('((likes >= 0))', name='check_likes'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='reviews_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name='reviews_parent_id')
    )
    op.create_index('reviews_created_at', 'reviews', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('reviews_is_open_likes_created_at', 'reviews', [sa.literal_column('is_open DESC'), sa.literal_column('likes DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('reviews_is_open_min_stars_likes_created_at', 'reviews', [sa.literal_column('is_open DESC'), 'stars', sa.literal_column('likes DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_index('reviews_is_open_stars_likes_created_at', 'reviews', [sa.literal_column('is_open DESC'), sa.literal_column('stars DESC'), sa.literal_column('likes DESC'), sa.literal_column('created_at DESC')], unique=False)
    op.create_table('school_post_clicks',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Идентификатор школьной публикации'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='school_post_clicks_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['school_posts.post_id'], name='school_post_clicks_post_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'post_id', name='school_post_clicks_parent_id_post_id')
    )
    op.create_index('school_post_clicks_created_at', 'school_post_clicks', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_post_clicks_post_id_parent_id', 'school_post_clicks', ['post_id', 'parent_id'], unique=False)
    op.create_table('school_post_likes',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Идентификатор школьной публикации'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='school_post_likes_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['school_posts.post_id'], name='school_post_likes_post_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'post_id', name='school_post_likes_parent_id_post_id')
    )
    op.create_index('school_post_likes_created_at', 'school_post_likes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_post_likes_post_id_parent_id', 'school_post_likes', ['post_id', 'parent_id'], unique=False)
    op.create_table('school_post_viewings',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Идентификатор школьной публикации'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='school_post_viewings_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['school_posts.post_id'], name='school_post_viewings_post_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'post_id', name='school_post_viewings_parent_id_post_id')
    )
    op.create_index('school_post_viewings_created_at', 'school_post_viewings', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_post_viewings_post_id_parent_id', 'school_post_viewings', ['post_id', 'parent_id'], unique=False)
    op.create_table('school_post_visions',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='Идентификатор школьной публикации'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='school_post_visions_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['school_posts.post_id'], name='school_post_visions_post_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'post_id', name='school_post_visions_parent_id_post_id')
    )
    op.create_index('school_post_visions_created_at', 'school_post_visions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('school_post_visions_post_id_parent_id', 'school_post_visions', ['post_id', 'parent_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='Идентификатор пользователя (пустой до авторизации)'),
    sa.Column('active_child_id', sa.BigInteger(), nullable=True, comment='Идентификатор активного ребенка (пустой до авторизации)'),
    sa.Column('dnevnik_token', sa.String(length=64), nullable=True, comment='API-токен Дневника.ру для взаимодействия с ним (пустой до авторизации)'),
    sa.Column('firebase_token', sa.String(length=4096), nullable=True, comment='Firebase-токен для отправки уведомлений (пустой до авторизации)'),
    sa.Column('life', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Сессия активна или больше не работает'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('((((parent_id IS NULL) = (dnevnik_token IS NULL)) AND ((parent_id IS NULL) = (active_child_id IS NULL))))', name='check_full_auth'),
    sa.ForeignKeyConstraint(['active_child_id'], ['children.child_id'], name='sessions_active_child_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='sessions_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name='sessions_pkey')
    )
    op.create_index('sessions_created_at', 'sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('sessions_life_parent_id_session_id', 'sessions', ['life', 'parent_id', 'session_id'], unique=False)
    op.create_index('sessions_parent_id_life_session_id', 'sessions', ['parent_id', 'life', 'session_id'], unique=False)
    op.create_index('sessions_parent_id_session_id', 'sessions', ['parent_id', 'session_id'], unique=False)
    op.create_table('caches',
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='Идентификатор ребенка'),
    sa.Column('key', sa.String(length=64), nullable=False, comment='Уникальный ключ кэша'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Значение кэша'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name='ea_processing_notifications_ea_child_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='ea_processing_notifications_ea_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'child_id', 'key', name='caches_session_id_key_child_id')
    )
    op.create_index('caches_created_at', 'caches', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('ea_notifications',
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='Идентификатор ребенка'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name='ea_notifications_child_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='ea_notifications_session_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id', 'session_id', name='ea_notifications_child_id_session_id')
    )
    op.create_index('ea_notifications_created_at', 'ea_notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('marks_notifications',
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии'),
    sa.Column('child_id', sa.BigInteger(), nullable=False, comment='Идентификатор ребенка'),
    sa.Column('last_mark', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Точное время постановки последней оценки от Дневника.ру'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], name='marks_notifications_child_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='marks_notifications_session_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id', 'session_id', name='marks_notifications_child_id_session_id')
    )
    op.create_index('marks_notifications_created_at', 'marks_notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('review_likes',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('review_id', sa.BigInteger(), nullable=False, comment='Идентификатор отзыва (идентификатор пользователя-владельца отзыва)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], name='likes_reviews_parent_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.parent_id'], name='likes_reviews_review_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'review_id', name='likes_reviews_parent_id_review_id')
    )
    op.create_index('review_likes_created_at', 'review_likes', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END; $$ LANGUAGE plpgsql;")
    op.execute("CREATE TRIGGER update_caches_updated_at BEFORE UPDATE ON caches FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_children_updated_at BEFORE UPDATE ON children FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_ea_notifications_updated_at BEFORE UPDATE ON ea_notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_ea_processing_notifications_updated_at BEFORE UPDATE ON ea_processing_notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_extracurricular_activities_updated_at BEFORE UPDATE ON extracurricular_activities FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_highlighting_persons_updated_at BEFORE UPDATE ON highlighting_persons FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_hours_updated_at BEFORE UPDATE ON hours FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_informations_updated_at BEFORE UPDATE ON informations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_lesson_notes_updated_at BEFORE UPDATE ON lesson_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_logs_updated_at BEFORE UPDATE ON logs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_marks_notifications_updated_at BEFORE UPDATE ON marks_notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_monitorings_updated_at BEFORE UPDATE ON monitorings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_notifications_updated_at BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_parents_updated_at BEFORE UPDATE ON parents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_ratings_updated_at BEFORE UPDATE ON ratings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_referrals_updated_at BEFORE UPDATE ON referrals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_review_likes_updated_at BEFORE UPDATE ON review_likes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_admins_updated_at BEFORE UPDATE ON school_admins FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_post_clicks_updated_at BEFORE UPDATE ON school_post_clicks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_post_likes_updated_at BEFORE UPDATE ON school_post_likes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_posts_updated_at BEFORE UPDATE ON school_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_post_viewings_updated_at BEFORE UPDATE ON school_post_viewings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_school_post_visions_updated_at BEFORE UPDATE ON school_post_visions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_sessions_updated_at BEFORE UPDATE ON sessions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_statistic_messages_updated_at BEFORE UPDATE ON statistic_messages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_statistics_updated_at BEFORE UPDATE ON statistics FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE TRIGGER update_versions_updated_at BEFORE UPDATE ON versions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();")
    op.execute("CREATE FUNCTION insert_ea_processing_notification() RETURNS TRIGGER AS $$ BEGIN INSERT INTO ea_processing_notifications (ea_id, start_time) VALUES (NEW.ea_id, NEW.start_time); RETURN NEW; END; $$ LANGUAGE plpgsql;")
    op.execute("CREATE TRIGGER insert_ea_processing_notifications AFTER INSERT ON extracurricular_activities FOR EACH ROW EXECUTE FUNCTION insert_ea_processing_notification();")
    op.execute("CREATE FUNCTION sync_ea_start_time() RETURNS TRIGGER AS $$ BEGIN IF (OLD.start_time IS DISTINCT FROM NEW.start_time) THEN UPDATE ea_processing_notifications SET start_time = NEW.start_time WHERE ea_id = NEW.ea_id; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;")
    op.execute("CREATE TRIGGER update_ea_processing_notifications_start_time AFTER UPDATE OF start_time ON extracurricular_activities FOR EACH ROW EXECUTE FUNCTION sync_ea_start_time();")
    op.execute("CREATE FUNCTION move_to_notifications() RETURNS TRIGGER AS $$ BEGIN INSERT INTO notifications (log_id, ip, path, session_id, status, method, value) VALUES (NEW.log_id, NEW.ip, NEW.path, NEW.session_id, NEW.status, NEW.method, NEW.value); RETURN NEW; END; $$ LANGUAGE plpgsql;")
    op.execute("CREATE TRIGGER log_move_to_notifications AFTER INSERT ON logs FOR EACH ROW EXECUTE FUNCTION move_to_notifications();")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('review_likes_created_at', table_name='review_likes')
    op.drop_table('review_likes')
    op.drop_index('marks_notifications_created_at', table_name='marks_notifications')
    op.drop_table('marks_notifications')
    op.drop_index('ea_notifications_created_at', table_name='ea_notifications')
    op.drop_table('ea_notifications')
    op.drop_index('caches_created_at', table_name='caches')
    op.drop_table('caches')
    op.drop_index('sessions_parent_id_session_id', table_name='sessions')
    op.drop_index('sessions_parent_id_life_session_id', table_name='sessions')
    op.drop_index('sessions_life_parent_id_session_id', table_name='sessions')
    op.drop_index('sessions_created_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('school_post_visions_post_id_parent_id', table_name='school_post_visions')
    op.drop_index('school_post_visions_created_at', table_name='school_post_visions')
    op.drop_table('school_post_visions')
    op.drop_index('school_post_viewings_post_id_parent_id', table_name='school_post_viewings')
    op.drop_index('school_post_viewings_created_at', table_name='school_post_viewings')
    op.drop_table('school_post_viewings')
    op.drop_index('school_post_likes_post_id_parent_id', table_name='school_post_likes')
    op.drop_index('school_post_likes_created_at', table_name='school_post_likes')
    op.drop_table('school_post_likes')
    op.drop_index('school_post_clicks_post_id_parent_id', table_name='school_post_clicks')
    op.drop_index('school_post_clicks_created_at', table_name='school_post_clicks')
    op.drop_table('school_post_clicks')
    op.drop_index('reviews_is_open_stars_likes_created_at', table_name='reviews')
    op.drop_index('reviews_is_open_min_stars_likes_created_at', table_name='reviews')
    op.drop_index('reviews_is_open_likes_created_at', table_name='reviews')
    op.drop_index('reviews_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('referrals_referral_id_parent_id', table_name='referrals')
    op.drop_index('referrals_parent_id_referral_id', table_name='referrals')
    op.drop_index('referrals_created_at', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ratings_period_id_child_id_subject_id', table_name='ratings')
    op.drop_index('ratings_created_at', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('notifications_status_created_at', table_name='notifications')
    op.drop_index('notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('lesson_notes_lesson_id_child_id', table_name='lesson_notes')
    op.drop_index('lesson_notes_created_at', table_name='lesson_notes')
    op.drop_table('lesson_notes')
    op.drop_index('informations_time', table_name='informations')
    op.drop_index('informations_created_at', table_name='informations')
    op.drop_table('informations')
    op.drop_index('highlighting_persons_created_at', table_name='highlighting_persons')
    op.drop_table('highlighting_persons')
    op.drop_index('ea_processing_notifications_start_time', table_name='ea_processing_notifications')
    op.drop_index('ea_processing_notifications_created_at', table_name='ea_processing_notifications')
    op.drop_table('ea_processing_notifications')
    op.drop_index('versions_created_at', table_name='versions')
    op.drop_table('versions')
    op.drop_index('tgbot_states_created_at', table_name='tgbot_states')
    op.drop_table('tgbot_states')
    op.drop_index('statistics_parent_id_key', table_name='statistics')
    op.drop_index('statistics_created_at', table_name='statistics')
    op.drop_table('statistics')
    op.drop_index('statistic_messages_created_at', table_name='statistic_messages')
    op.drop_table('statistic_messages')
    op.drop_index('school_posts_school_id_created_at', table_name='school_posts')
    op.drop_index('school_posts_created_at', table_name='school_posts')
    op.drop_table('school_posts')
    op.drop_index('school_admins_school_id_user_id', table_name='school_admins')
    op.drop_index('school_admins_school_id_person_id', table_name='school_admins')
    op.drop_index('school_admins_parent_admin_user_id', table_name='school_admins')
    op.drop_index('school_admins_created_at', table_name='school_admins')
    op.drop_table('school_admins')
    op.drop_index('parents_created_at', table_name='parents')
    op.drop_table('parents')
    op.drop_index('monitorings_status_path_session_id_duration', table_name='monitorings')
    op.drop_index('monitorings_status_path_duration', table_name='monitorings')
    op.drop_index('monitorings_path_session_id_duration', table_name='monitorings')
    op.drop_index('monitorings_path_duration', table_name='monitorings')
    op.drop_index('monitorings_created_at', table_name='monitorings')
    op.drop_table('monitorings')
    op.drop_index('logs_status_created_at', table_name='logs')
    op.drop_index('logs_created_at', table_name='logs')
    op.drop_table('logs')
    op.drop_index('hours_school_id_months_weekdays', table_name='hours')
    op.drop_index('hours_created_at', table_name='hours')
    op.drop_table('hours')
    op.drop_index('extracurricular_activities_start_time_subject_place', table_name='extracurricular_activities')
    op.drop_index('extracurricular_activities_created_at', table_name='extracurricular_activities')
    op.drop_table('extracurricular_activities')
    op.drop_index('children_school_id_group_id_child_id', table_name='children')
    op.drop_index('children_created_at', table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION move_to_notifications();")
    op.execute("DROP FUNCTION sync_ea_start_time();")
    op.execute("DROP FUNCTION insert_ea_processing_notification();")
    op.execute("DROP FUNCTION update_updated_at_column();")
