"""add school_admins.life

Revision ID: cfd65bf7037a
Revises: ce5a2755b274
Create Date: 2026-06-16 13:38:44.529098+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd65bf7037a'
down_revision: Union[str, Sequence[str], None] = 'ce5a2755b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_admins', sa.Column('life', sa.Boolean(), nullable=True, comment='Сессия администратора образовательной организации активна или больше не работает'))
    # ### end Alembic commands ###

    op.drop_constraint("check_type_admin", "school_admins", type_="check")
    op.execute("UPDATE school_admins SET life = true WHERE parent_admin_id IS NULL")
    op.create_check_constraint(
        "check_type_admin",
        "school_admins",
        "((((parent_admin_id IS NULL) <> (person_id IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (school_id IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (dnevnik_token IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (timezone IS NULL))))"
        "AND ((parent_admin_id IS NULL) <> (life IS NULL))"
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION get_root_admin_id(start_user_id BIGINT)
        RETURNS BIGINT
        LANGUAGE sql
        STABLE
        AS $$
            WITH RECURSIVE hierarchy AS (
                SELECT
                    user_id,
                    parent_admin_id
                FROM school_admins
                WHERE user_id = start_user_id
        
                UNION ALL
        
                SELECT
                    a.user_id,
                    a.parent_admin_id
                FROM school_admins a
                JOIN hierarchy h
                    ON a.user_id = h.parent_admin_id
            )
            SELECT user_id
            FROM hierarchy
            WHERE parent_admin_id IS NULL
            LIMIT 1;
        $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_admins', 'life')
    # ### end Alembic commands ###

    op.execute("DELETE FUNCTION get_root_admin_id(start_user_id BIGINT)")
    op.drop_constraint("check_type_admin", "school_admins", type_="check")
    op.create_check_constraint(
        "check_type_admin",
        "school_admins",
        "((((parent_admin_id IS NULL) <> (person_id IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (school_id IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (dnevnik_token IS NULL)) "
        "AND ((parent_admin_id IS NULL) <> (timezone IS NULL))))"
    )
