"""Web session

Revision ID: e55a0298e395
Revises: fb0b496e76fa
Create Date: 2026-09-26 08:17:00.335791+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55a0298e395'
down_revision: Union[str, Sequence[str], None] = 'fb0b496e76fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_sessions',
    sa.Column('web_session_id', sa.String(length=32), nullable=False, comment='Идентификатор web-сессии'),
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='Идентификатор сессии'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='web_sessions_session_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('web_session_id', name='web_sessions_pkey'),
    sa.UniqueConstraint('session_id', name='web_sessions_ukey')
    )
    op.create_index('web_sessions_created_at', 'web_sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('web_sessions_life', 'web_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('web_sessions_life', table_name='web_sessions')
    op.drop_index('web_sessions_created_at', table_name='web_sessions')
    op.drop_table('web_sessions')
    # ### end Alembic commands ###
