"""Update marks notifications

Revision ID: fb0b496e76fa
Revises: 1df5d7c26d31
Create Date: 2026-09-24 14:36:59.157824+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0b496e76fa'
down_revision: Union[str, Sequence[str], None] = '1df5d7c26d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks_notifications', sa.Column('active_period_id', sa.BigInteger(), nullable=True, comment='Идентификатор текущего отчетного периода'))
    op.add_column('marks_notifications', sa.Column('marks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='Все оценки за текущий отчетный период'))
    op.alter_column('marks_notifications', 'marks', server_default=None)
    op.add_column('marks_notifications', sa.Column('marks_hash', sa.String(length=64), server_default=sa.text("''"), nullable=False, comment='Хэш списка оценок алгоритмом SHA-256'))
    op.alter_column('marks_notifications', 'marks_hash', server_default=None)
    op.drop_column('marks_notifications', 'last_mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks_notifications', sa.Column('last_mark', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False, comment='Точное время постановки последней оценки от Дневника.ру'))
    op.drop_column('marks_notifications', 'marks_hash')
    op.drop_column('marks_notifications', 'marks')
    op.drop_column('marks_notifications', 'active_period_id')
    # ### end Alembic commands ###
